### ISSUE TITLE
beeflow --version command needed

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#529]
Might be nice to support this version command

**Comment by rstyd** [comment]
In order to support this, we're going to need a VERSION file in the root BEE directory. Then add a `--version` parameter to beeflow that uses this VERSION file. For, now the version can be something arbitrary like `0.1`.

**Comment by pagrubel** [comment]
The version is in the pyproject.toml file. See the line ``version = "0.1.0rc1"``.   If you cannot use that, we will need to modify version in two places.

**Comment by aquan9** [comment]
It's a little complicated to get Typer "options" working in conjunction with Typer "subcommands", After digging through the docs I found that you need to use an app.callback() to get an option working outside of the subcommand. 
See the following:
https://typer.tiangolo.com/tutorial/commands/callback/

In addition since it's used without a subcommand you need to call it as @app.callback(invoke_without_command=True)

See the following:
https://cloudbytes.dev/snippets/set-the-default-command-in-python-typer-cli


So now you would just call "beeflow --version", and it is able to regex for the version string mentioned above in the pyproject.toml file and print it out.
