### ISSUE TITLE
BEE error message change

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#618]
I mistyped the name for the yml file and got this message.

```
An error occurred with the WFM. Please save your workflow and the
error log "bee-error-1669681893.log". If possible, please report this
to the BEE development team.
```

Upon examining the log I found my error. I think we should change this message to check "bee-error...log" 
When would we want them to report it to us? Not for a typo that's for sure.

**Comment by jtronge** [comment]
This suggests that we're either not checking the yml file name, or that there's some other related error in the WFM. I think the user should report this error message because it indicates there's a bug in our code, rather than in what the user submitted.

This error message is printed whenever the WFM returns a 500 error, meaning there was an uncaught exception. Ideally we should probably catch common errors like this and return an error message to the user like `Input yml file '....' does not exist`.

**Comment by pagrubel** [comment]
Issue #584 could be related

**Comment by pagrubel** [comment]
Closing this since the error is now caught.
