### ISSUE TITLE
Remove delay time after workflow submit

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#705]
When we submit a workflow, there is a delay while the workflow manager waits for the neo4j instance to finish loading. We should offload the wait to a subprocess and instantly return a workflow ID to the user after we parse the workflow in the client.

**Comment by pagrubel** [comment]
I still think there is the possibility of someone wanting to submit another workflow immediately. Since you will most likely create a new workflow state (Submitting) so I guess we could check for that state before attempting another and a message could come back, "Another workflow is in Submitting state, please submit when it finishes submission" or something like that.)

**Comment by rstyd** [comment]
If someone submits another workflow immediately, it won't be a problem since the previous workflow submission will be worked on by another process and we'll just fork a new processes for the new workflow.

**Comment by pagrubel** [comment]
Fixed in #728
