### ISSUE TITLE
Can't cancel --no-start workflow

### ISSUE THREAD

**Issue by Leahh02** [lanl/BEE#901]
I tried to cancel a workflow that had a 'Waiting' status and got message ``Workflow is Waiting cannot cancel.`` and then I tried to pause it and nothing happened and then I tried to remove it and got message
``` 
Workflow Status is Waiting
37f4f1 may still be running.
The workflow must be cancelled before attempting removal.
```
This all started because I tried to do `beeflow submit --no-start` and then I didn't want to run it anymore. I was working on the "Multiple-Workflows-One-Database" branch, but I'm guessing this problem isn't just specific to that branch.

**Comment by pagrubel** [comment]
The reason we don't allow cancel for workflows that are in WAITING state is probably because we assumed WAITING means building a container. We may need to add a state for that or at least handle this well when the state is because of building a container.
Another thought is can we have a NO START state for those that are submitted with the no-start flag?

**Comment by pagrubel** [comment]
This is working for Workflows that have been submitted with the --no-start flag.
